### ISSUE TITLE
Errors running simple example

### ISSUE THREAD

**Issue by freiguy1** [japaric/cortex-m-rtfm#91]
Hello there. I'm sure the issue is something I overlooked, but I'm attempting to get the `zero-tasks.rs` example working with the blue pill.

Cargo.toml:
```toml
[dependencies]
cortex-m-rtfm = "0.3.4"

[dependencies.stm32f103xx]
features = ["rt"]
version = "0.10.0"
```

main.rs: literally copied from `examples/zero-tasks.rs` in repo

Rust & Cargo versions:
```
rustc 1.30.0-nightly (5c875d938 2018-09-24)
cargo 1.31.0-nightly (de314a8b2 2018-09-21)
```

`cargo build` output:
```text
error: `#[panic_handler]` function required, but not found

error: aborting due to previous error

error: Could not compile `testing`.
```
